# Generated by Django 4.2.6 on 2023-10-29 02:46

from django.db import migrations, models
import userpuzzle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_name', models.CharField(max_length=50, verbose_name='puzzle_name')),
                ('puzzle_description', models.CharField(max_length=50, verbose_name='puzzle_description')),
                ('user_name', models.CharField(max_length=16, verbose_name='user_name')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload_date')),
                ('puzzle_image', models.ImageField(upload_to=userpuzzle.models.upload_path, verbose_name='puzzle_image')),
                ('encoded_hint', models.CharField(max_length=960, verbose_name='encoded_hint')),
                ('hint_count', models.IntegerField(verbose_name='hint_count')),
                ('puzzle_hash', models.CharField(max_length=12, verbose_name='puzzle_hash')),
            ],
        ),
    ]
